### ISSUE TITLE
浏览器刷新后do play failed问题

### ISSUE THREAD

**Issue by liyoro** [langyuxiansheng/vue-aliplayer-v2#10]
又发现一个奇怪的问题了source写死直播的地址，第一次进入是do play successfully的，这时候F5刷新，就会do play failed了，很奇怪的问题。局network里面查看，视频流还是在推送的。这问题cctv上偶尔出现，在我实际用上是必然出现

**Comment by langyuxiansheng** [comment]
最新的版本上还有有这个问题吗?

**Comment by liyoro** [comment]
是的，我试了vue-aliplayer，也是有这个问题

**Comment by langyuxiansheng** [comment]
好的 我测试一下看看

**Comment by langyuxiansheng** [comment]
do play failed 这个应该是Alipayer里输出的,测试地址  //ivi.bupt.edu.cn/hls/cctv1.m3u8    但是播放是正常的.
![image](https://user-images.githubusercontent.com/29669030/83614753-3762aa80-a5b8-11ea-9032-42a2a1b9db9f.png)

**Comment by liyoro** [comment]
多试试，有时候正常，有时候播不了，比较神奇。
可以尝试下别的直播源

**Comment by langyuxiansheng** [comment]
好的  我后面持续关注一下

**Comment by chaojiangcn** [comment]
我这正常视频也是这样
