### ISSUE TITLE
请教下，关闭播放器窗口，播放器在后台一直在运行

### ISSUE THREAD

**Issue by Jonauil** [langyuxiansheng/vue-aliplayer-v2#13]
import VueAliplayer from 'vue-aliplayer-v2'
components: {
    VueAliplayer: VueAliplayer.Player
  },
<vue-aliplayer ref="VueAliplayer" :source="dataForm.videoUrl"  />

关闭窗口，调用播放器销毁方法无法：
     this.dataForm.videoUrl = ''
      this.$refs.VueAliplayer.pause()
      this.$refs.VueAliplayer.dispose()

浏览器console窗口一直输出，请求视频资源
_reloadForVod
reload vod because failed
aliplayer-min.js:2 do play

**Comment by langyuxiansheng** [comment]
感谢反馈，这个问题我下周测试一下看看，应该很快就能处理的。

**Comment by langyuxiansheng** [comment]
感谢您的反馈与建议,bug已经修复.如果您正在使用,请稍后更新到最新版即可
