### ISSUE TITLE
更新1.2.1后报错Uncaught TypeError: 没有为播放器指定容器

### ISSUE THREAD

**Issue by liyoro** [langyuxiansheng/vue-aliplayer-v2#16]
更新1.2.1后报错Uncaught TypeError: 没有为播放器指定容器，可以播放，但是报错
![Snip20200708_9](https://user-images.githubusercontent.com/1903138/86907508-bd3dbc80-c147-11ea-9011-470437b4104d.png)

**Comment by langyuxiansheng** [comment]
感谢反馈,因为源码中变更了部分代码,以及最大限度的简化代码,组件内部的根容器就只有一个div容器,导致以前外部指定id的时候,容器id与外部的不一致,导致抛出异常了,现在已经紧急修复了,若在使用,请更新到v1.2.2的版本;如果使用了外部指定id的方式请移除外部的id.否则id会出现重复的情况.


![image](https://user-images.githubusercontent.com/29669030/86993218-06d4e880-c1d6-11ea-98f0-88f5db1dd450.png)
