### ISSUE TITLE
组件components args传递vue里面的变量，得出来的都是undefined

### ISSUE THREAD

**Issue by waiting0729** [langyuxiansheng/vue-aliplayer-v2#19]
vue里面的变量定义：
`data() {
    return {
      videoSpeed: '2.0',
}`
定义components是：
`options: {
        source: '//player.alicdn.com/video/aliyunmedia.mp4',
        height: '500px',
        controlBarVisibility: 'always',
        rePlay: true,
        autoplay: true,
        skinLayout: [
          { name: 'bigPlayButton', align: 'blabs', x: 30, y: 80 },
          {
            name: 'H5Loading', align: 'cc'
          },
          { name: 'errorDisplay', align: 'tlabs', x: 0, y: 0 },
          { name: 'infoDisplay' },
          { name: 'tooltip', align: 'blabs', x: 0, y: 56 },
          { name: 'thumbnail' },
          {
            name: 'controlBar', align: 'blabs', x: 0, y: 0,
            children: [
              { name: 'progress', align: 'blabs', x: 0, y: 44 },
              { name: 'playButton', align: 'tl', x: 15, y: 12 },
              { name: 'timeDisplay', align: 'tl', x: 10, y: 7 },
              { name: 'fullScreenButton', align: 'tr', x: 10, y: 12 },
            ]
          }
        ],
        components: [
          { name: 'RateComponent', type: RateComponent, args: [this.videoSpeed1] }
        ]
      },
`
在components构造函数的打印参数：
`
constructor (rate) {
    console.log('constructor!!!')
    var rateHtml = '<div class="rate-components">\n' +
      '  <div class="current-rate">1.0x</div>\n' +
      '  <ul class="rate-list">\n' +
      '    <li data-rate="2.0">2.0x</li>\n' +
      '    <li data-rate="1.5">1.5x</li>\n' +
      '    <li data-rate="1.25">1.25x</li>\n' +
      '    <li data-rate="1.0" class="current">1.0x</li>\n' +
      '    <li data-rate="0.5">0.5x</li>\n' +
      '  </ul>\n' +
      '</div>'
    this.html = parseDom(rateHtml)
    this.rate = rate
    console.log('rate --->', rate)
  }`
rate打印出来的值都是undefined
`
components: [
          { name: 'RateComponent', type: RateComponent, args: ['2.0'] }
        ]`
经过测试上面代码是能直接传递过去的，请问有哪位大兄弟遇到过这种情况，又是怎么解决的呢

**Comment by langyuxiansheng** [comment]
你这个是需要重新封装 还是需要扩展功能呢

**Comment by waiting0729** [comment]
重新写了一个播放倍速的components,rate 死活传不过去我也是纳闷

**Comment by waiting0729** [comment]
> 你这个是需要重新封装 还是需要扩展功能呢

重新写了一个播放倍速的components,实现连续播放的时候继承上一个视频设置的倍速
