### ISSUE TITLE
请问播放中如何用方法设置音量

### ISSUE THREAD

**Issue by kason888** [langyuxiansheng/vue-aliplayer-v2#20]
没找到音量设置相关的属性，请帮忙看一下呗，感谢(●'◡'●)

**Comment by langyuxiansheng** [comment]
文档地址：https://help.aliyun.com/document_detail/125572.html?spm=a2c4g.11186623.6.1085.36fc6fc57WKZ5P#h2-u64ADu653Eu5668u63A5u53E32

this.$refs.XXXX.setVolume() 参数为0-1之间的数

**Comment by langyuxiansheng** [comment]
设置音量，vol为0-1的实数，ios和部分android会失效。
