### ISSUE TITLE
传id无效

### ISSUE THREAD

**Issue by 865077695** [langyuxiansheng/vue-aliplayer-v2#22]
我看源码里props里的id怎么注释起来了，不支持外部传入id了吗？
![image](https://user-images.githubusercontent.com/19943886/92703950-2ed2fa80-f385-11ea-8250-7f5357cb237b.png)

**Comment by langyuxiansheng** [comment]
你好  感谢反馈, 
在v1.2.2 版本更新中有说明,主要是外部传入的id容易出现bug,容易错误和重复,所以现在都改为内部生成的方式了

**Comment by 865077695** [comment]
@langyuxiansheng 嗯嗯，看到了，random生成id，那确实不需要了，谢谢。
