### ISSUE TITLE
微信中首次加载直播时无法播放，后续可以正常加载直播

### ISSUE THREAD

**Issue by laowantong2077** [langyuxiansheng/vue-aliplayer-v2#23]
我猜测是因为添加的<script type="text/javascript" id="aliplayer-min-js" src="https://g.alicdn.com/de/prismplayer/2.8.2/aliplayer-min.js"></script> 还未生效，请问有什么好的解决方法吗？

**Comment by langyuxiansheng** [comment]
请问一下应用场景呢,目前我这边线上也有项目在使用,http://saxdweb.mingchulz.com:8088/#/merchantDetail/831847919135  也是正常的,js都会等待onloa方法加载完才会进行初始化的

**Comment by sbbs3626** [comment]
<template v-if="datail.liveUrl">
				<vue-aliplayer-v2
					:source="datail.liveUrl"
					ref="VideoPlayer"
					:options="options"
					@play="_play"
					@liveStreamStop="_liveStreamStop"
					@error="_error"
				/>
			</template>

**Comment by laowantong2077** [comment]
```
<template v-if="datail.liveUrl">
				<vue-aliplayer-v2
					:source="datail.liveUrl"
					ref="VideoPlayer"
					:options="options"
					@play="_play"
					@liveStreamStop="_liveStreamStop"
					@error="_error"
				/>
			</template>
```

组件是全局注册的，axios 请求接口后返回监控地址，  PC调试正常， 微信中第一次打开 不正常加载视频，后续进入正常

**Comment by langyuxiansheng** [comment]
好的  我测试一下看看呢,你那边的视频是直播流还是普通的视频呢

**Comment by laowantong2077** [comment]
监控直播流，.m3u8 

--------------补充
我尝试加了一个手动点击播放后，第一次加载视频也能成功，估计加载 cdn aliplayer-min.js 还是需要时间的

**Comment by langyuxiansheng** [comment]
我看了一下,控制台会出现 do play > do play failed 的提示. 你也是使用自动加载和自动播放的情况出现的吗

**Comment by laowantong2077** [comment]
是自动加载和自动播放的，pc上模拟调试没有问题，手机上加载不行，你刚才项目里tab选项卡把视频放第一个加载能手机上正常播放吗

**Comment by langyuxiansheng** [comment]
我是本地直接跑的插件开发版项目进行测试的,你也可以直接下载这个项目,然后本地 npm run dev 进行调试一下,这个自动播放的,阿里云官方的文档描述比较模糊, 

preload | Boolean | 播放器自动加载，目前仅h5可用。
-- | -- | --

autoplay | Boolean | 播放器是否自动播放，在移动端autoplay属性会失效。Safari11不会自动开启自动播放如何开启。
-- | -- | --

 这有两个属性,可能都会出现do play failed的情况

**Comment by laowantong2077** [comment]
谢谢解答，我自己再尝试一下

**Comment by langyuxiansheng** [comment]
感谢反馈,若线上交流不方便,可以加我VX: zlj520213 或者 QQ: 1096432931 可以一起研究一下.

**Comment by laowantong2077** [comment]
还是浏览器安全策略问题， 移动端不支持自动播放。
