### ISSUE TITLE
ios 可以 全屏播放？

### ISSUE THREAD

**Issue by liangzhiyuan2015** [langyuxiansheng/vue-aliplayer-v2#25]
作者你好！我再使用得时候，再ios手机上看视频得时候 好像不能全屏。然后 我试了一下 ios设置里面得 打开转圈那个图标 然后就可以进行全屏播放拉。

**Comment by langyuxiansheng** [comment]
一般情况下可能是开启了强制竖屏(也就是屏幕锁定)打开后就会竖屏而不会全屏了！如下关闭就可以了：

1. 开启了屏幕锁定，只要上拉控制中心，点击屏幕锁定关闭就可以了！
![image](https://user-images.githubusercontent.com/29669030/94380400-f6defc00-0167-11eb-827a-350785c0955d.png)

2. 也可能是播放器或者浏览器兼容性问题.

**Comment by langyuxiansheng** [comment]
感谢反馈,o(*￣︶￣*)o

**Comment by liangzhiyuan2015** [comment]
好的，收到！谢谢作者！
