### ISSUE TITLE
播放源是否可动态变更

### ISSUE THREAD

**Issue by wikimo** [langyuxiansheng/vue-aliplayer-v2#3]
播放源配置options.source尝试通过变量进行设置并没有效果，调用loadByUrl也不是很理想，是否有其它更好的解，谢谢。

**Comment by langyuxiansheng** [comment]
感谢你的建议,我看看在下一个版本中能否处理一下,目前只是对阿里云的这个进行了一次简单的封装,保留了大部分原生的方法,

**Comment by wikimo** [comment]
https://github.com/slacrey/vue-aliplayer/blob/master/src/VueAliplayer.vue-> reloadPlayer 能解，但感觉不是很好。一般情况下，source都是动态从后端获取的。

**Comment by langyuxiansheng** [comment]
![image](https://user-images.githubusercontent.com/29669030/76938428-8c840e00-6931-11ea-8b1d-22e276b33cd0.png)
感谢您的反馈,您提的这个功能建议已采纳,并在v1.1.7的版本中实现.更新到最新版本 并使用source属性即可
