### ISSUE TITLE
rtmp 格式直播切换到 hls 格式时黑屏

### ISSUE THREAD

**Issue by litmonw** [langyuxiansheng/vue-aliplayer-v2#31]
由于看到文档 source 动态切换不支持直播，于是我将直播地址放到 options.source 之中，但是当 options.source 改变时，直播切换了，有了对应地址的音频，但是视频没有显示。

我试过当 options.source 修改后，使用 replay() 方法也没有产生作用。

**Comment by langyuxiansheng** [comment]
你好 感谢反馈,请问您使用的版本是多少的版本呢,可以先去阿里云那边测试一下看看呢

**Comment by litmonw** [comment]
> 你好 感谢反馈,请问您使用的版本是多少的版本呢,可以先去阿里云那边测试一下看看呢

vue-aliplayer-v2 是 1.2.5，js 版本源默认。
直播源地址我测过单个都是没有问题的。切换的时候出现了问题。

**Comment by langyuxiansheng** [comment]
能提供一下直播源嘛 因为这边底层也是使用的阿里云的SDK

**Comment by litmonw** [comment]
> 能提供一下直播源嘛 因为这边底层也是使用的阿里云的SDK

rtmp://ivi.bupt.edu.cn:1935/livetv/chchd
https://6.mms.vlog.xuite.net/hls/ftvtv/index.m3u8
https://live.cgtn.com/1000/prog_index.m3u8

**Comment by langyuxiansheng** [comment]
阿里云那边的文档中写的,不支持rtmp流直接切换,如果有这需求估计要重新处理一下才行呀

**Comment by litmonw** [comment]
> 阿里云那边的文档中写的,不支持rtmp流直接切换,如果有这需求估计要重新处理一下才行呀

我对阿里云的 aliplayer 不太熟悉，重新处理的话是要销毁重建吗？还是说有更好的办法？

**Comment by langyuxiansheng** [comment]
我测试了一下,销毁重新创建是正常的,如果直接切换就会无法播放,因为rtmp的流使用了flash播放器,m3u8是使用的js

**Comment by litmonw** [comment]
> 我测试了一下,销毁重新创建是正常的,如果直接切换就会无法播放,因为rtmp的流使用了flash播放器,m3u8是使用的js

谢谢。

**Comment by langyuxiansheng** [comment]
【/手动捂脸】

**Comment by litmonw** [comment]
> 【/手动捂脸】

抱歉，仍然遇到了问题，我使用了方法 dispose 和 你演示 demo 里的 if 两种方式销毁，但是都遇到了报错或异常情况。

**Comment by langyuxiansheng** [comment]
这个不同格式切换的场景，我确实还没遇到，如果SDK不支持的话，毕竟底层是aliplayer，只能看一下其它版本的SDK版本了，【/抱歉】
