### ISSUE TITLE
禁止拖动

### ISSUE THREAD

**Issue by lutao1997** [langyuxiansheng/vue-aliplayer-v2#32]
希望可以加一个禁止用户拖动视频进度的配置项，下面是我自己写的禁止拖动
`if (
          currentTime > this.playTime + 2 ||
          currentTime < this.playTime - 2
        ) {
          return this.$refs.VueAliplayerV2.seek(this.playTime);
        } else {
          this.playTime = currentTime;
        }`

但是会有问题，设置禁止拖动后，虽然记录了播放进度，但是再次进入的时候因为设置了禁止拖动，所以seek事件失效

**Comment by langyuxiansheng** [comment]
感谢建议与反馈,这个播放器的底层是基于Alipayer进行封装的,方法是直接映射,没有其它的冗余封装,官方提供了一个禁止拖动的属性:disableSeek:true和useFlashPrism:true(仅flash模式有效),这两个属性同时配合使用即可禁止进度条了,另一个方案就是 直接设置属性isLive:true. 在直播模式下也是不允许进度条的.

底层SDK文档https://help.aliyun.com/document_detail/125572.html?spm=a2c4g.11186623.6.1175.586b476aLbtX4V

**Comment by lutao1997** [comment]
不行啊，我这边的需求是，虽然要禁止用户拖动，但是如果设置了直播模式，暂停功能将无法使用

**Comment by langyuxiansheng** [comment]
![image](https://user-images.githubusercontent.com/29669030/100824164-9c785980-3490-11eb-97d8-20f238aeafe6.png)
那可以暂时先用一下flash模式吧. 

还有就是 "....，但是再次进入的时候因为设置了禁止拖动，所以seek事件失效",这个是你这边需要使用这两个回调吗?

startSeek | 开始拖拽，参数返回拖拽点的时间。
-- | --
completeSeek

**Comment by langyuxiansheng** [comment]
如果你这边只是想禁止让用户拖动进度条,或者只是让用户看,不显示进度条的情况下,可以使用皮肤定制功能,
https://help.aliyun.com/document_detail/62947.html?spm=a2c4g.11186623.2.19.4a535259xbtihs

只屏蔽进度条的情况下,别的功能不受影响.

![image](https://user-images.githubusercontent.com/29669030/100824604-74d5c100-3491-11eb-872b-71c60c8ebd09.png)

**Comment by lutao1997** [comment]
不是这个回调，因为我自己设置了禁止拖动，seek事件我指的是设置跳转到某个时间继续播放，比如用户浏览到三分钟的时候关了视频，即进度为三分钟，下次再次进入这个视频，应该跳转到三分钟继续播放，但因为我设置了进度条改变两秒以上即视为拖动了进度条，所以会回到视频刚开始

**Comment by langyuxiansheng** [comment]
> 不是这个回调，因为我自己设置了禁止拖动，seek事件我指的是设置跳转到某个时间继续播放，比如用户浏览到三分钟的时候关了视频，即进度为三分钟，下次再次进入这个视频，应该跳转到三分钟继续播放，但因为我设置了进度条改变两秒以上即视为拖动了进度条，所以会回到视频刚开始

可以加个我的微信,方便交流. zlj520213
