### ISSUE TITLE
局部注册找不到组件

### ISSUE THREAD

**Issue by jieruian** [langyuxiansheng/vue-aliplayer-v2#4]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <vue-aliplayer-v2> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in
按照文档局部引入主键，注册了组件后，但是识别不了

**Comment by langyuxiansheng** [comment]
感谢您的反馈，问题我再检查一下看看，如果存在问题，会在下一个版本中更新

**Comment by langyuxiansheng** [comment]
感谢您的反馈，问题我再检查一下看看，如果存在问题，会在下一个版本中更新

**Comment by langyuxiansheng** [comment]
感谢您的反馈,您提的这个问题已处理.
