### ISSUE TITLE
播放M3U8视频 本地播放没问题 发布到线上报 Uncaught TypeError: Cannot read property 'readyState' of null

### ISSUE THREAD

**Issue by jujingyi0618** [langyuxiansheng/vue-aliplayer-v2#41]

**Comment by langyuxiansheng** [comment]
感谢反馈,如果线上地址是公开的,能否留个链接呢

**Comment by jujingyi0618** [comment]
https://cychengyuan-vod.48.cn/607591/20210114/cy/556258190046334976-jh1bju7b5v8dqp2ykfcm.m3u8
这个potplayer也可以直接播放

**Comment by langyuxiansheng** [comment]
> https://cychengyuan-vod.48.cn/607591/20210114/cy/556258190046334976-jh1bju7b5v8dqp2ykfcm.m3u8
> 这个potplayer也可以直接播放

[捂脸] 我刚刚看了一下,数据状态是正常的,视频是黑屏的吗?

**Comment by jujingyi0618** [comment]
https://cychengyuan-vod.48.cn/867891/20210112/cy/555836914022551552-ezw95nfqrf80j68wrlw2.m3u8
刚刚那个是电台 黑屏有声音，这个是视频
在本地都正常播放，但打包发布线上就报这个错误 error信息是 获取M3U8文件超时

**Comment by langyuxiansheng** [comment]
> https://cychengyuan-vod.48.cn/867891/20210112/cy/555836914022551552-ezw95nfqrf80j68wrlw2.m3u8
> 刚刚那个是电台 黑屏有声音，这个是视频
> 在本地都正常播放，但打包发布线上就报这个错误 error信息是 获取M3U8文件超时

![image](https://user-images.githubusercontent.com/29669030/104673111-08024780-571c-11eb-9c57-38d7352a3528.png)
我在demo上测试是正常的, 请查看一下你本地的npm包版本,目前最新版是1.2.8的,

**Comment by jujingyi0618** [comment]
"vue-aliplayer-v2": "^1.2.8",
是最新版 奇了怪了

**Comment by langyuxiansheng** [comment]
> "vue-aliplayer-v2": "^1.2.8",
> 是最新版 奇了怪了

我也有点奇了怪了......... 为啥会有这种问题

**Comment by jujingyi0618** [comment]
> > "vue-aliplayer-v2": "^1.2.8",
> > 是最新版 奇了怪了
> 
> 我也有点奇了怪了......... 为啥会有这种问题

我把你的demo代码复制一份 也是本地切换都正常 发布线上M3U8报这个错，播放我先单独用html页面写吧，这个可以播放

**Comment by langyuxiansheng** [comment]
> > > "vue-aliplayer-v2": "^1.2.8",
> > > 是最新版 奇了怪了
> > 
> > 
> > 我也有点奇了怪了......... 为啥会有这种问题
> 
> 我把你的demo代码复制一份 也是本地切换都正常 发布线上M3U8报这个错，播放我先单独用html页面写吧，这个可以播放

这个只有后面看一下吧. 收到的问题里... 目测就只有你这边遇到的问题... 如果是压缩包的问题,你可以试一下将源码的组件 放到本地项目里测试一下看看.

**Comment by MrTung** [comment]
我也遇到相同的情况了，这是奇怪
