### ISSUE TITLE
frame ready callback function ?

### ISSUE THREAD

**Issue by lihongyi1234** [langyuxiansheng/vue-aliplayer-v2#42]
hello ,thank  you for your aliplayer vue project , i tested it and it works, I have a question that if i can get texture when every frame decode finished? i need the texture information, looking forward for your reply...

**Comment by langyuxiansheng** [comment]
Thank you for your feedback,at present, vue-aliplayer-v2 is encapsulated based on aliplayer's SDK. For specific attributes, please refer to: https://help.aliyun.com/document_ detail/125572.html?spm=a2c4g.11186623.6.1179.131d10e4Ib3fpW

**Comment by lihongyi1234** [comment]
ok, thank you
