### ISSUE TITLE
v1.2.8版本，不显示进度条

### ISSUE THREAD

**Issue by MrSSai** [langyuxiansheng/vue-aliplayer-v2#44]
使用code下面的示例代码，不显示进度条控制面板，设置 `controlBarVisibility:"always"`也是不显示

**Comment by langyuxiansheng** [comment]
感谢反馈, 请问你配置项的代码中isLive 是否为true呢,如果是的话,在直播模式下是无法显示进度条的,
` options: {
                // source:'//player.alicdn.com/video/aliyunmedia.mp4',
                isLive: true,   //切换为直播流的时候必填
                // format: 'm3u8'  //切换为直播流的时候必填
            },`

**Comment by MrSSai** [comment]
问题应该是版本问题。

我使用同一份代码，将配置项中isLive设为false，controlBarVisibility设为always。`options: { // source:'//player.alicdn.com/video/aliyunmedia.mp4', isLive: false, //切换为直播流的时候必填 // format: 'mp4', //切换为直播流的时候必填controlBarVisibility:'always' },`

使用v1.2.8版本不显示进度条
使用v1.2.7版本可以显示进度条

**Comment by langyuxiansheng** [comment]
> 问题应该是版本问题。
> 
> 我使用同一份代码，将配置项中isLive设为false，controlBarVisibility设为always。`options: { // source:'//player.alicdn.com/video/aliyunmedia.mp4', isLive: false, //切换为直播流的时候必填 // format: 'mp4', //切换为直播流的时候必填controlBarVisibility:'always' },`
> 
> 使用v1.2.8版本不显示进度条
> 使用v1.2.7版本可以显示进度条

那可能是SDK的问题了。 最近GitHub老是登不了。。。。
