### ISSUE TITLE
vue2.9环境下使用，无法显示按钮

### ISSUE THREAD

**Issue by Schean17** [langyuxiansheng/vue-aliplayer-v2#47]
加载视频后，无法显示底栏，对播放器界面点击无响应
vue2.9版本，npm下引入的，全局注册和局部注册都测试过了，一样的；有什么解决方法吗
![image](https://user-images.githubusercontent.com/49357727/115532124-171f0580-a2c8-11eb-8f9c-2680ce5ccd65.png)

**Comment by langyuxiansheng** [comment]
感谢反馈. 我记得是直播模式下,有些配置是不会显示按钮的.

**Comment by langyuxiansheng** [comment]
可以先看一下配置项

**Comment by Schean17** [comment]
![image](https://user-images.githubusercontent.com/49357727/115534668-97df0100-a2ca-11eb-802e-fb800df3fa0c.png)
点播模式下的，直播模式下页应该有状态栏的啊

**Comment by langyuxiansheng** [comment]
> ![image](https://user-images.githubusercontent.com/49357727/115534668-97df0100-a2ca-11eb-802e-fb800df3fa0c.png)
> 点播模式下的，直播模式下页应该有状态栏的啊

昨天晚上回去,电脑坏了.... 待我电脑修好之后来看看呢....

**Comment by Schean17** [comment]
options里加上skinLayout的话是能正常显示的，但是不加的话，默认模式下的按钮布局显示不出来

**Comment by langyuxiansheng** [comment]
已修复了,原因是内置的配置项中有皮肤的属性设置,
