### ISSUE TITLE
解决了我遇到的问题

### ISSUE THREAD

**Issue by Hxmic** [langyuxiansheng/vue-aliplayer-v2#5]
还有没有其他视频播放的组件

**Comment by langyuxiansheng** [comment]
目前只集成了阿里云的这个播放器控件,别的暂时没有了

**Comment by ghost** [comment]
1.1.7 版本 使用 this.$refs.VueAliplayerV2.getStatus() 报错

**Comment by langyuxiansheng** [comment]
> 1.1.7 版本 使用 this.$refs.VueAliplayerV2.getStatus() 报错
您好  感谢您的反馈,报错问题在1.1.8的版本已修复.报错原因:多写了一次fullscreenService.getIsFullScreen.
