### ISSUE TITLE
在nuxt中使用报错 Uncaught TypeError: 没有为播放器指定容器

### ISSUE THREAD

**Issue by Bruce-Ming** [langyuxiansheng/vue-aliplayer-v2#50]
在页面间跳转进入视频播放页没问题,但是在视频播放页刷新就会报错 Uncaught TypeError: 没有为播放器指定容器

**Comment by langyuxiansheng** [comment]
感谢反馈,目前还没测试过nuxt的场景,后面我测试一些看看

**Comment by xiaoma13** [comment]
你好 请问 你这个问题解决了吗  一模一样的 bug

**Comment by Bruce-Ming** [comment]
> 你好 请问 你这个问题解决了吗  一模一样的 bug

没有。换了一个别的播放器。

**Comment by xiaoma13** [comment]
换的什么播放器 @Bruce-Ming

**Comment by Bruce-Ming** [comment]
> 换的什么播放器 @Bruce-Ming 

Vue-Video-Player git星最多的
