### ISSUE TITLE
source 类型不对

### ISSUE THREAD

**Issue by vanche-phe** [langyuxiansheng/vue-aliplayer-v2#7]
您好，请问动态换源怎么设置的，Invalid prop: type check failed for prop "source". Expected Object, got String with value "".

**Comment by langyuxiansheng** [comment]
好的我检查一下

**Comment by langyuxiansheng** [comment]
感谢您的反馈，您提的问题在1.1.9的版本中已经修复了，原因是定义的String的类型，然后默认值返回的是 （)=> null
