### ISSUE TITLE
关于直播hls的奇怪问题

### ISSUE THREAD

**Issue by liyoro** [langyuxiansheng/vue-aliplayer-v2#8]
例如：直播地址http://ivi.bupt.edu.cn/hls/cctv1.m3u8
直接设置source: 'http://ivi.bupt.edu.cn/hls/cctv1.m3u8',的时候，播放是ok的，但是通过方法动态设置source的时候，就无法播放了，例如在getCurrentTime设置

getCurrentTime(){ 
  this.source = 'http://ivi.bupt.edu.cn/hls/cctv1.m3u8'
},

这时候就播放失败了，请问是什么问题啊，这个是必然出现的问题

**Comment by langyuxiansheng** [comment]
感谢您的反馈,您的问题已经收到,正在进行验证和处理

**Comment by liyoro** [comment]
找到问题所在了，需要reload一下，vue-aliplayer里面的方法可以用的
const player = this.$refs.aliplayer
 player && player.reloadPlayer()
主要是调用reloadPlayer这个方法，
你添加下这个方法就可以了

**Comment by liyoro** [comment]
找到问题所在了，在vue-aliplayer里面有方法的，主要是改变source后要reload player一下。
const player = this.$refs.aliplayer
player && player.reloadPlayer()
你添加下reloadPlayer方法就可以了

**Comment by langyuxiansheng** [comment]
感谢您的反馈和建议,这个bug已经修复了,在1.2.0的版本中
